### ISSUE TITLE
Issue with natural reinforcement 

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#75] opened 2012-10-20 23:11 UTC
16:13:40 [SEVERE] [Citadel] Internal error!
16:13:40 [SEVERE] [Citadel] Include the following into your bug report:
16:13:40 [SEVERE] [Citadel]           ======= SNIP HERE =======
16:13:40 [SEVERE] [Citadel] java.lang.NullPointerException
16:13:40 [SEVERE] [Citadel]     at com.untamedears.citadel.entity.Reinforcement.getHealth(Reinforcement.java:119)
16:13:40 [SEVERE] [Citadel]     at com.untamedears.citadel.entity.Reinforcement.getHealthText(Reinforcement.java:123)
16:13:40 [SEVERE] [Citadel]     at com.untamedears.citadel.entity.Reinforcement.getStatus(Reinforcement.java:142)
16:13:40 [SEVERE] [Citadel]     at com.untamedears.citadel.listener.PlayerListener.interact(PlayerListener.java:148)
16:13:40 [SEVERE] [Citadel]     at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
16:13:40 [SEVERE] [Citadel]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:13:40 [SEVERE] [Citadel]     at java.lang.reflect.Method.invoke(Method.java:601)
16:13:40 [SEVERE] [Citadel]     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
16:13:40 [SEVERE] [Citadel]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
16:13:40 [SEVERE] [Citadel]     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
16:13:40 [SEVERE] [Citadel]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467)
16:13:40 [SEVERE] [Citadel]     at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
16:13:40 [SEVERE] [Citadel]     at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:98)
16:13:40 [SEVERE] [Citadel]     at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:545)
16:13:40 [SEVERE] [Citadel]     at net.minecraft.serverhook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:114)
16:13:40 [SEVERE] [Citadel]     at net.minecraft.server.Packet14BlockDig.handle(SourceFile:43)
16:13:40 [SEVERE] [Citadel]     at net.minecraft.server.NetworkManager.b(NetworkManager.java:234)
16:13:40 [SEVERE] [Citadel]     at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:119)
16:13:40 [SEVERE] [Citadel]     at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:83)
16:13:40 [SEVERE] [Citadel]     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:579)
16:13:40 [SEVERE] [Citadel]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
16:13:40 [SEVERE] [Citadel]     at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
16:13:40 [SEVERE] [Citadel]           ======= SNIP HERE =======

**Comment by ttk2** [comment] 2012-10-20 23:29
This issue causes naturally reinforced ores to break on the first break and is of course a major problem.

**Comment by ghost** [comment] 2012-10-21 17:08
Correct me if I'm wrong since I'm not too familiar with java, but shouldn't catching the exception, re-pulling the value from the db, then calling the method again be sufficient for this one?

(Sorry that I can't test this myself, the bug report doesn't tell how to reproduce and I didn't encounter it while I was playing afaik)

**Comment by ttk2** [comment] 2012-10-21 17:15
A bit kludgy but it could work. I should probably GI ahead and clarify that
the bounties are for fixes not kludges but we could work with that sort of
solution although I would not close the issue until we had a real fix.

**Comment by ghost** [comment] 2012-10-21 18:30
does citadel handle all of its own db stuff? It seems like the fix would be more an issue with the database caching than citadel itself, if not.

edit: also I don't care so much about the bounties, I basically just want civtest back up :)

**Comment by ttk2** [comment] 2012-10-21 19:41
Citadel uses libraries to handle a great deal of its db stuff.

**Comment by ghost** [comment] 2012-10-21 19:55
So wouldn't it make more sense to put it up as a bug against whatever library, since the cache apparently drops blocks it needs sometimes? Until then I'll try to track down a way to force a refresh on the cache which should hopefully temporarily patch this.

**Comment by ttk2** [comment] 2012-10-21 20:20
Until its positively confirmed that it is the library we will assume its
not, we are using popular systems with a lot more time and effort put into
them than all of Citadel (not to insult our programmers, they are just more
popular projects) the chance of it being an error with our minimally tested
code over their library is massive.

**Comment by uncorr** [comment] 2012-10-21 20:31
This looks like it's a problem with the natural reinforcer assigning the material with which the block was naturally reinforced.  Diving deeper.

**Comment by uncorr** [comment] 2012-10-21 20:36
Yeah.  When the plugin queries what % health a Reinforcement is at, instead of storing the denominator directly, it makes a reference to the material that was used to reinforce it.

What material is used to reinforce a natural reinforcement is irrelevant because bypassing is impossible.  Erocs was right that Reinforcement should be made into IReinforcement and have NaturalReinforcement and PlayerReinforcement implement it, but I'll fix with an if statement as a stopgap measure.  At least, this is my best idea so far.

**Comment by ttk2** [comment] 2012-10-21 20:49
Go ahead and fix it right, the last thing Citadel needs is another stopgap.

**Comment by erocs** [comment] 2012-10-22 20:23
This specific issue was fixed with pull #77.

**Comment by ttk2** [comment] 2012-10-22 20:24
I will close it next time I am at a computer.

**Closed as completed** 2012-10-22 21:38 UTC
